version: '3'

services:
  app:
    build:
      context: ./
    container_name: weatherapi_app
    ports:
      - "8000:80"
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always
    networks:
      default:

  postgres:
    image: postgres:latest
    container_name: weatherapi_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      default:
